- name: Update the system repository (Debian based systems)
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Add podman to all nodes
  become: true
  ansible.builtin.apt:
    name:
      - python3
      - podman
      - catatonit
      - chrony
      - lvm2
      - systemd
    install_recommends: no
    state: present

- name: Ensure chronyd is running
  become: true
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: true
